// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

import { databaseConfig } from "./src/lib/database-url";
if (process.env.MATHS4U_BUILD !== "1" && process.env.MATHS4U_ENV !== "production") config({ path: ".env.local", quiet: true });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env.MATHS4U_BUILD !== "1" && process.env.MATHS4U_DATABASE_URL ? databaseConfig().raw : undefined,
  },
});
