import { test } from "node:test";
import assert from "node:assert/strict";
import { readFile, writeFile } from "node:fs/promises";
import { db } from "../src/lib/prisma";
import { userSelect, transaction } from "../src/lib/security";
import { requirePilotDatabase } from "../scripts/pilot/import";
import { beginStudy, revealStudyHelp, selfCheckStudy, topicStudy } from "../src/lib/study";
import { getAttempt, mutateAttempt, createWork, workSchema } from "../src/lib/works";
import { download } from "../src/lib/files";
import { progress } from "../src/lib/courses";
import { topicContent, courseCatalog } from "../src/lib/catalog";
import { saveStructure } from "../src/lib/structure";
import { saveTask, publicVersion, versionInclude, exportTask, taskSchema } from "../src/lib/content";
import { auditStorage, retryDeletedCleanup } from "../src/lib/storage-maintenance";
import { POST, GET } from "../src/app/api/[...path]/route";

test("real pilot study, per-material help, ungraded self-check, assigned restrictions and structure edits", { timeout: 120000 }, async t => {
  requirePilotDatabase();
  const f = JSON.parse(await readFile(".local/content-pilot-correction/preview.json", "utf8"));
  const actor = (username: string) => db().user.findUniqueOrThrow({ where: { username }, select: userSelect });
  const template = await db().user.findUniqueOrThrow({ where: {username:f.student} });
  const fresh = (name:string) => db().user.create({data:{username:name+Date.now(),displayName:"Local study QA",passwordHash:template.passwordHash,roles:{create:{role:"STUDENT"}}},select:userSelect});
  const student = await fresh("study_"), other = await fresh("study_other_"), teacher = await actor(f.teacher), admin = await actor(f.admin);
  const olymp = await db().lesson.findFirstOrThrow({ where: { topic: { course: { slug: "olymp-number-theory2" } } }, include: { tasks: { orderBy: { position: "asc" } } } });
  const maths = await db().lessonTask.findFirstOrThrow({ where: { taskId: f.taskIds[0], lesson: {topic: {course: {slug:"maths4u-0606"}}} } });
  const starts = await Promise.all([beginStudy(student, { taskId: olymp.tasks[0].taskId, lessonId: olymp.id }, "en"), beginStudy(student, { taskId: olymp.tasks[0].taskId, lessonId: olymp.id }, "ru")]);
  const id = starts[0].id;
  await t.test("concurrent starts reuse one attempt; help is explicit and localized; manual self-check never grades", async () => {
    assert.equal(starts[1].id, id);
    let dto = await getAttempt(student, id, "en");
    assert.equal(dto.manager, false); assert.ok(dto.questions[0].availableHelp?.hint); assert.ok(dto.questions[0].availableHelp?.solution);
    assert.equal(dto.questions[0].hint, undefined); assert.equal(dto.questions[0].solution, undefined); assert.equal(dto.questions[0].markScheme, undefined);
    await assert.rejects(selfCheckStudy(student, id, { state: "SELF_CHECKED" }), /SUBMIT_BEFORE_SELF_CHECK/);
    await revealStudyHelp(student, id, { kind: "hint" }, "en");
    dto = await getAttempt(student, id, "en"); assert.ok(dto.questions[0].hint); assert.equal(dto.questions[0].solution, undefined);
    const ru = await getAttempt(student, id, "ru"); assert.ok(ru.questions[0].hint); assert.notEqual(ru.questions[0].hint, dto.questions[0].hint);
    await mutateAttempt(student, id, { revision: dto.revision, answers: [{ partId: dto.questions[0].parts[0].id, response: { value: "My independent reasoning" } }] });
    dto = await getAttempt(student, id); assert.equal((dto.answers[0].response as {value:string}).value, "My independent reasoning");
    await mutateAttempt(student, id, { revision: dto.revision, answers: [] }, true);
    await revealStudyHelp(student, id, { kind: "solution" }, "ru");
    await selfCheckStudy(student, id, { state: "SELF_CHECKED" });
    dto = await getAttempt(student, id); assert.equal(dto.status, "SUBMITTED"); assert.equal(dto.answers[0].points, null); assert.equal(dto.pendingReview, true); assert.ok(dto.study?.selfCheckedAt);
    await selfCheckStudy(student, id, { state: "NEEDS_REPEAT" });
    await progress(student, olymp.id, { completed: true });
    const p = await topicStudy(student, olymp.id, "ru");
    assert.equal(p.items[0].state, "NEEDS_REPEAT"); assert.equal(p.items[0].helpUsed, true); assert.equal(p.completedWithoutHelp, 0); assert.equal(p.theoryRead, true); assert.ok(p.history.some(h => h.id === id));
    const next = await beginStudy(student, { taskId: olymp.tasks[1].taskId, lessonId: olymp.id }, "ru");
    assert.equal((await topicStudy(student, olymp.id, "en")).items[1].attemptId, next.id);
    await assert.rejects(revealStudyHelp(other, id, { kind: "solution" }, "en"), /STUDY_ONLY/);
    await assert.rejects(selfCheckStudy(other, id, { state: "SELF_CHECKED" }), /STUDY_ONLY/);
    await assert.rejects(revealStudyHelp(student, f.attemptId, { kind: "markScheme" }, "en"), /STUDY_ONLY/);
    await assert.rejects(selfCheckStudy(student, f.attemptId, { state: "SELF_CHECKED" }), /STUDY_ONLY/);
  });
  await t.test("MS stays separate and direct material URLs follow explicit authorization", async () => {
    const correction = JSON.parse(await readFile(".local/content-pilot-correction/correction.json", "utf8"));
    const row = correction.tasks[0], record = await db().importRecord.findUniqueOrThrow({ where: { sourceProject_legacyId: { sourceProject: "maths4u", legacyId: row.legacyId } } });
    const a = await beginStudy(other, { taskId: record.taskId!, lessonId: maths.lessonId }, "en");
    const before = await getAttempt(other, a.id, "en"); assert.equal(before.questions[0].availableHelp?.markScheme, true);
    await assert.rejects(download(other, row.files[0].id));
    await revealStudyHelp(other, a.id, { kind: "markScheme" }, "en");
    const after = await getAttempt(other, a.id, "en"); assert.ok(after.questions[0].markScheme); assert.equal(after.questions[0].solution, undefined);
    const onlyMs = await saveTask(admin,{texts:[{locale:"en",title:"Synthetic MS-only QA",statement:"Question",markScheme:"Independent marking guidance",markSchemeSource:"Author rubric"}],parts:[{kind:"MANUAL",maxPoints:1,texts:[{locale:"en",prompt:"Explain"}]}]});
    const only = publicVersion(await db().taskVersion.findUniqueOrThrow({where:{id:onlyMs.id},include:versionInclude}),"en",true);
    assert.equal(only.solution,""); assert.ok(only.markScheme);
    const exported = taskSchema.parse((await exportTask(admin, onlyMs.taskId)).records[0].material);
    assert.equal(exported.texts[0].markScheme,"Independent marking guidance");assert.equal(exported.texts[0].markSchemeSource,"Author rubric");
    const storage=await auditStorage(); assert.ok(storage.originalDiskBytes>0);assert.ok(storage.derivativeDiskBytes>0); assert.equal(storage.missingActiveFiles,0);
    const clean=await retryDeletedCleanup();assert.equal(clean.originalDiskBytes,storage.originalDiskBytes);assert.equal(clean.derivativeDiskBytes,storage.derivativeDiskBytes); assert.equal(clean.pendingCleanupBytes,0);
    for (const variant of ["original", "preview", "thumbnail"]) assert.ok((await download(other, row.files[0].id, variant)).data.length);
    await assert.rejects(download(null, row.files[0].id));
    await assert.rejects(transaction(tx => createWork(tx, teacher, workSchema.parse({ title: "No provisional ranking", kind: "OLYMPIAD", taskIds: [olymp.tasks[0].taskId], opensAt: new Date(), dueAt: new Date(Date.now()+60000) }))), /PROVISIONAL_OLYMPIAD_SCORE/);
    const api = (method: "POST"|"GET", route: string, body?: unknown) => (method === "POST" ? POST : GET)(new Request(process.env.APP_URL + "/api/" + route, { method, headers: { origin: process.env.APP_URL!, "content-type": "application/json" }, ...(body ? {body:JSON.stringify(body)} : {}) }), { params: Promise.resolve({path:route.split("/")}) });
    assert.equal((await api("POST", "study/start", {taskId:record.taskId})).status, 401);
    assert.equal((await api("POST", `attempts/${a.id}/help`, {kind:"markScheme"})).status, 401);
  });
  await t.test("administrator can order and share task links without changing tasks or old lesson versions", async () => {
    await assert.rejects(saveStructure(teacher, {}), /FORBIDDEN/);
    const c = await saveStructure(admin, {kind:"course", slug:"structure-"+Date.now(), position:7, published:false, texts:[{locale:"en",title:"Structure QA"}]});
    const chapter = await saveStructure(admin, {kind:"chapter",parentId:c.id,slug:"chapter",position:2,texts:[{locale:"en",title:"Chapter"}]});
    const input = {kind:"topic",parentId:chapter.id,position:3,texts:[{locale:"en",title:"Topic",body:"<p>Original</p>",examples:"<p>Example</p>"}],taskIds:f.taskIds.slice(0,2)};
    const topic = await saveStructure(admin, input), versions = await db().taskVersion.count();
    assert.equal((await courseCatalog(student,"en")).some(row=>row.id===c.id),false);
    await saveStructure(admin, {kind:"course",id:c.id,position:1,published:true,texts:[{locale:"en",title:"Structure QA"}]});
    const original = await db().lessonVersion.findFirstOrThrow({where:{lessonId:topic.id},include:{texts:true}});
    await saveStructure(admin,{...input,id:topic.id,taskIds:[...input.taskIds].reverse(),texts:[{...input.texts[0],body:"<p>New text</p>"}]});
    assert.equal((await db().lessonText.findUniqueOrThrow({where:{versionId_locale:{versionId:original.id,locale:"en"}}})).body,"<p>Original</p>");
    assert.equal(await db().taskVersion.count(),versions);
    assert.deepEqual((await db().lessonTask.findMany({where:{lessonId:topic.id},orderBy:{position:"asc"}})).map(l=>l.taskId),[...input.taskIds].reverse());
    assert.equal((await topicContent(student,topic.id,"en")).body,"<p>New text</p>");
    assert.equal(await db().lessonTask.count({where:{lessonId:maths.lessonId}}),36);
  });
  await writeFile(".local/content-pilot-correction/study-preview.json",JSON.stringify({lessonId:olymp.id,courseSlug:"olymp-number-theory2",taskIds:olymp.tasks.map(t=>t.taskId),attemptId:id}));
  await db().$disconnect();
});
