import { test, expect } from "@playwright/test";
import fs from "node:fs/promises";
test("teacher selects across topics and pages, reloads, reorders and assigns a single work", async ({ page }) => {
  const login = JSON.parse(await fs.readFile(".local/content-pilot-correction/preview.json", "utf8")), catalog = JSON.parse(await fs.readFile(".local/content-pilot-correction/catalog-preview.json", "utf8"));
  await page.goto("/teacher/works/new"); await page.locator('input[name="username"]').fill(login.teacher); await page.locator('input[name="password"]').fill(login.password); await page.locator('form button[type="submit"]').click();
  await expect(page.getByRole('heading', { name: /^(Assign work|Назначить работу)$/ })).toBeVisible();
  await page.getByRole('button', { name: 'RU', exact: true }).click();
  await page.goto("/library");
  const basket = page.getByRole('region', { name: 'Набор задач', exact: true });
  if (await basket.getByRole('button', { name: 'Очистить', exact: true }).count()) await basket.getByRole('button', { name: 'Очистить', exact: true }).click();
  await page.getByLabel("Курс", { exact: true }).selectOption(catalog.courseId);
  await page.getByLabel("Тема", { exact: true }).selectOption(catalog.lessonIds[0]);
  await expect(page.locator('.catalog-total')).toHaveText("Доступно задач: 60");
  await page.locator('.task-select input').first().check(); await expect(basket.getByRole('status')).toHaveText('1 задач · 2 баллов');
  await page.getByRole('navigation', { name: 'Страницы задач' }).getByRole('button', { name: 'Далее →' }).click();
  await expect(page.locator('.task-number').first()).toHaveText('26');
  await page.locator('.task-select input').first().check(); await expect(basket.getByRole('status')).toHaveText('2 задач · 4 баллов');
  await page.getByLabel("Тема", { exact: true }).selectOption(catalog.lessonIds[1]);
  await expect(page.locator('.task-number').first()).toHaveText('1');
  await page.locator('.task-select input').first().check(); await expect(basket.getByRole('status')).toHaveText('3 задач · 6 баллов');
  await page.getByRole('button', { name: 'EN', exact: true }).click(); await expect(page.getByLabel('Topic', { exact: true })).toHaveValue(catalog.lessonIds[1]);
  await page.reload();
  const englishBasket = page.getByRole('region', { name: 'Task set', exact: true }); await expect(englishBasket.getByRole('status')).toHaveText('3 tasks · 6 points');
  const title = await englishBasket.locator('li strong').nth(2).innerText();
  await englishBasket.locator('li').nth(2).getByRole('button', { name: /^Move up:/ }).click();
  await expect(englishBasket.locator('li strong').nth(1)).toContainText(title.replace(/^3\. /, ''));
  await page.screenshot({ path: '.local/content-pilot-correction/catalog-desktop.png', fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: '.local/content-pilot-correction/catalog-mobile.png', fullPage: true });
  await englishBasket.getByRole('link', { name: 'Create homework / test', exact: true }).click();
  await page.locator('input[name="title"]').fill('UI: two topics in one work'); await page.locator('select[name="classId"]').selectOption(login.classId);
  const response = page.waitForResponse(r => r.url().endsWith('/api/works') && r.request().method() === 'POST');
  await page.getByRole('button', { name: 'Assign to students', exact: true }).click();
  const created = await response; expect(created.status()).toBe(201); const work = await created.json();
  await expect(page).toHaveURL(new RegExp(`/works/${work.id}/results$`));
  await expect(page.getByRole('heading', { name: 'UI: two topics in one work', exact: true })).toBeVisible();
});
