import { test, expect } from "@playwright/test";
import fs from "node:fs/promises";
test("teacher reviews scans and PDF, keeps drafts across tabs, language, navigation and reload", async ({ page }) => {
  const fixture = JSON.parse(await fs.readFile(".local/content-pilot-correction/preview.json", "utf8"));
  const errors: string[] = []; page.on("pageerror", e => errors.push(e.message));
  await page.goto(`/attempts/${fixture.attemptId}/review`);
  await page.locator('input[name="username"]').fill(fixture.teacher);
  await page.locator('input[name="password"]').fill(fixture.password);
  await page.locator('form button[type="submit"]').click();
  await expect(page.locator('.review-screen')).toBeVisible();
  await page.getByRole('button', { name: 'RU', exact: true }).click();
  await expect(page.getByRole("heading", { name: "Ответ ученика", exact: true })).toBeVisible();
  await expect(page.locator('.review-answer .viewer-viewport img')).toBeVisible();
  await expect(page.locator('.review-reference .viewer-viewport img')).toBeVisible();
  await expect(page.getByLabel("Баллы", { exact: true })).toHaveValue("");
  await page.getByLabel("Комментарий ученику", { exact: true }).fill("Комментарий: производная и нормаль; сохранить без оценки.");
  await expect(page.getByRole("status", { name: "" }).filter({ hasText: /^Сохранено$/ })).toBeVisible();
  await page.reload(); await expect(page.getByLabel("Баллы", { exact: true })).toHaveValue("");
  await expect(page.getByLabel("Комментарий ученику", { exact: true })).toHaveValue("Комментарий: производная и нормаль; сохранить без оценки.");
  await page.locator('.review-answer .viewer-thumbnails button').filter({ hasText: 'PDF' }).click();
  await expect(page.locator('.review-answer canvas')).toBeVisible();
  await expect(page.getByLabel("Страница PDF")).toHaveAttribute('max', '2');
  await page.getByLabel("Страница PDF").fill("2");
  await expect.poll(() => page.locator('.review-answer canvas').evaluate((e: HTMLCanvasElement) => e.width)).toBeGreaterThan(300);
  await page.screenshot({ path: ".local/content-pilot-correction/review-desktop.png", fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.locator('.review-mobile-tabs').getByRole('button', { name: 'Оценка', exact: true }).click();
  await expect(page.getByLabel("Комментарий ученику", { exact: true })).toBeVisible();
  await page.getByLabel("Комментарий ученику", { exact: true }).fill("Мобильный комментарий: x² + y² = 25");
  await page.locator('.review-mobile-tabs').getByRole('button', { name: 'MS', exact: true }).click();
  await expect(page.locator('.review-reference .viewer-viewport img')).toBeVisible();
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: ".local/content-pilot-correction/review-mobile.png", fullPage: true });
  await page.locator('.review-mobile-tabs').getByRole('button', { name: 'Оценка', exact: true }).click();
  await expect(page.getByLabel("Комментарий ученику", { exact: true })).toHaveValue("Мобильный комментарий: x² + y² = 25");
  await page.getByRole('button', { name: 'EN', exact: true }).click();
  await expect(page.getByLabel('Feedback for student', { exact: true })).toHaveValue("Мобильный комментарий: x² + y² = 25");
  await expect(page.getByLabel('Points', { exact: true })).toHaveValue("");
  await expect(page.getByRole('status').filter({ hasText: /^Saved$/ })).toBeVisible();
  await page.setViewportSize({width:1280,height:900});
  await page.getByLabel('Feedback for student',{exact:true}).fill("Saved before next task and student");
  await page.locator('.review-nav').getByRole('button',{name:'→',exact:true}).click();
  await expect(page.locator('.review-nav')).toContainText('2 / 2');
  await page.locator('.review-nav').getByRole('button',{name:'←',exact:true}).click();
  await expect(page.getByLabel('Feedback for student',{exact:true})).toHaveValue("Saved before next task and student");
  await page.getByRole('button',{name:'Next student →',exact:true}).click();
  await expect(page).toHaveURL(new RegExp(`/attempts/${fixture.peerAttemptId}/review$`));
  await page.goto(`/attempts/${fixture.attemptId}/review`);
  await expect(page.getByLabel('Feedback for student',{exact:true})).toHaveValue("Saved before next task and student");
  expect(errors).toEqual([]);
});
