ALTER TABLE `TaskVersion` ADD COLUMN `difficultyKnown` BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN `materialCategory` ENUM('UNKNOWN','EXAM','TRAINING','OLYMPIAD') NOT NULL DEFAULT 'UNKNOWN';
CREATE TABLE `TaskBasket` (
  `userId` VARCHAR(191) NOT NULL,
  `taskIds` JSON NOT NULL,
  `revision` INTEGER NOT NULL DEFAULT 0,
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`userId`),
  CONSTRAINT `TaskBasket_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
